services:
  - type: web
    name: video-trimmer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --timeout 600 --workers 2 --limit-request-line 0 --limit-request-field_size 0
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: RENDER
        value: "true"
